try {
  console.log(name);
  const name = "Fábio Júlio";
} catch (err) {
  console.log("Error: ", err);
}

console.log("Keep Going...");
